server:
  port: 8081
spring:
  application:
    name: Employs
  datasource:
    url: jdbc:h2:mem:employeedb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true